### ISSUE TITLE
Normalize UI

### ISSUE THREAD

**Issue by damiencriado** [emilyemorehouse/spacegray-peacock-ui#1]
Hi,

Why do you overwrite `@font-size` with 11px; and `@font-family` with 'Source Code Pro' ?

I think :

``` css
@font-size: 13px;
@font-family-code: 'Lucida Grande', 'Segoe UI', sans-serif;
```

Are best settings and standardizes the user interface with the default Atom theme :smile:

**Comment by emilyemorehouse** [comment]
Source Code Pro is the example font for the Spacegray theme that this is ported from, so I chose to keep the font from there. I also personally think that the default font size of 13px is too large. I didn't think too much about that one since the user can use their preferred font size easily.

**Comment by damiencriado** [comment]
I'm OK with the Source Code Pro font used, but in the syntax :

If you overwrite the font and size, Atom settings page change.
![atom](https://cloud.githubusercontent.com/assets/3238220/3037627/2c268ce8-e0c2-11e3-94fa-eeb454bb972e.png)

The font family AND the font size for the SYNTAX must be chose here, Atom offers these settings...
![capture decran 2014-05-21 a 10 30 47](https://cloud.githubusercontent.com/assets/3238220/3037631/368c1bd0-e0c2-11e3-979d-970c970f923b.png)

No ?
